# Generated by Django 3.1.12 on 2022-10-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='platform',
            field=models.CharField(choices=[('df', 'Default'), ('gl', 'Google')], default='df', max_length=2),
        ),
    ]
