# Generated by Django 3.1.12 on 2022-10-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_register_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='platform',
            field=models.CharField(choices=[('Default', 'df'), ('Google', 'gl')], default='df', max_length=7),
        ),
    ]
