# Generated by Django 3.1.12 on 2022-11-02 17:25

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MailTracking', '0002_auto_20221101_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailSenderModel',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=30, null=True)),
                ('mail_id', models.CharField(blank=True, max_length=20, null=True)),
                ('to_mail', models.CharField(blank=True, max_length=100, null=True)),
                ('from_mail', models.CharField(blank=True, max_length=100, null=True)),
                ('mail_sent', models.BooleanField(default=True)),
                ('mail_body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'db_mail_sender',
            },
        ),
    ]
